version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: vuln_dashboard
    volumes:
      - pgdata:/var/lib/postgresql/data
    # No ports -> not accessible from host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    working_dir: /app
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://dev:devpass@db:5432/vuln_dashboard
      SECRET_KEY: supersecretkey
    ports:
      - "9001:8000"  # Expose FastAPI backend only
    depends_on:
      - db

volumes:
  pgdata:
